### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by AlexWayfer** [kallepersson/tabswitcher#3]
Hello!

It's cool that I can open extension pop-up via hot-keys (`Ctrl+Shift+K`).

But I want navigate through list of tabs via keyboard too. With arrows and page keys (up and down).

Text (search) field in focus after opening pop-up, yes. But maybe it doesn't need these (vertical) keys. Or at least after `Tab`-key pressing…

Thanks.

**Comment by kallepersson** [comment]
Patches welcome :).
